plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://thingking-machine.github.io
baseurl: /wenq

title: Thingking Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Thingking-Machine
  verb: Thingking
  instructions_file: thingking.txt
  token: qrog.txt
  apiUrl: https://api.groq.com/openai/v1/chat/completions

app:
  worker_name: qrogapi.js

lm:
  model: qwen/qwen3-32b
  max_completion_tokens: 40960
  presence_penalty: 0.0
  temperature: 1.0
  top_p: 0.95
  reasoning_effort: default
  reasoning_format: raw


github_settings:
  owner: thingking-machine
  repo: thingking_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
